### ISSUE TITLE
Update for mastodon 2.0.0

### ISSUE THREAD

**Issue by RX14** [kirakiratter/mastodon#22]
Seems mastodon 2.0.0 has added custom theme support in https://github.com/tootsuite/mastodon/pull/4959. Would it be possible to update this theme to be compatible with mastodon 2.0.0?

**Comment by walfie** [comment]
unfortunately no one on the team (myself included) has had the time to work on the 2.0 CSS updates, but eventually it'll happen, I'm just not sure when..

**Comment by walfie** [comment]
well we finally updated to v2.4.1 today, so it's been updated. there may be a few style bugs though, which will be fixed as people find issues.
