### ISSUE TITLE
Profile Links & hashtags miscoloured

### ISSUE THREAD

**Issue by MasterDalK** [kirakiratter/mastodon#29]
Before:
![image](https://user-images.githubusercontent.com/24326990/41502391-0e92cd18-7187-11e8-9736-f715287561d9.png)

After:
![image](https://user-images.githubusercontent.com/24326990/41502384-d7bcaaac-7186-11e8-8e2e-9a085de92cac.png)

**Comment by walfie** [comment]
Fixed
![screen shot 2018-06-17 at 2 06 21 pm](https://user-images.githubusercontent.com/11370525/41510737-a992063e-7237-11e8-9faf-1cc1aed1bd88.png)
