### ISSUE TITLE
List Search illegible

### ISSUE THREAD

**Issue by MasterDalK** [kirakiratter/mastodon#34]
![image](https://user-images.githubusercontent.com/24326990/41502535-24b6c204-718a-11e8-8ed5-190d8715783d.png)
https://kirakiratter.com/@aikatsukamen/100216586608813731

**Comment by walfie** [comment]
fixed
![screen shot 2018-06-17 at 12 39 03 pm](https://user-images.githubusercontent.com/11370525/41510745-c49e9762-7237-11e8-8fef-e20357e352ef.png)

![screen shot 2018-06-17 at 12 38 57 pm](https://user-images.githubusercontent.com/11370525/41510749-cb2ac2cc-7237-11e8-829a-a4e4c34a2f45.png)
