### ISSUE TITLE
background-colors of followers page when "Hide your network" applied

### ISSUE THREAD

**Issue by unarist** [kirakiratter/mastodon#41]
![image](https://user-images.githubusercontent.com/705555/41503164-51219742-7207-11e8-9bf3-09125368bf97.png)

**Comment by walfie** [comment]
fixed
![screen shot 2018-06-17 at 2 10 20 pm](https://user-images.githubusercontent.com/11370525/41510778-328f672e-7238-11e8-8be2-96fff075e2ca.png)
