### ISSUE TITLE
Warnings on setting pages should have more contrast between text and background

### ISSUE THREAD

**Issue by unarist** [kirakiratter/mastodon#42]
![image](https://user-images.githubusercontent.com/705555/41503196-073cb142-7208-11e8-920f-1d66992ae056.png)

![image](https://user-images.githubusercontent.com/705555/41503212-59043f40-7208-11e8-8acd-8d1bf31155d7.png)

**Comment by walfie** [comment]
updated
![screen shot 2018-06-17 at 2 11 14 pm](https://user-images.githubusercontent.com/11370525/41510784-51ca3402-7238-11e8-9877-4eb0dc38b327.png)
